import { PageHeader } from '@/components/PageHeader';
import { FileText, Download, Printer, CheckCircle2, AlertTriangle, TrendingUp, Anchor } from 'lucide-react';

export function ReportsPage() {
  const today = new Date();
  const dateStr = today.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  const timeStr = today.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' });

  return (
    <div className="p-6 md:p-8 space-y-6 max-w-screen-2xl fade-in-up">
      <PageHeader
        title="Operations Brief"
        subtitle="Daily operational report for port commanders and duty officers"
        actions={
          <div className="flex items-center gap-2">
            <button className="flex items-center gap-1.5 px-4 py-2 text-[12px] font-medium bg-white border border-[#DCE3E8] text-[#617080] rounded-lg hover:bg-[#F3F8FC] transition-colors no-print">
              <Printer className="w-3.5 h-3.5" />
              Print
            </button>
            <button
              className="flex items-center gap-1.5 px-4 py-2 text-[12px] font-bold text-white rounded-lg transition-all no-print"
              style={{ background: '#1677C8' }}
            >
              <Download className="w-3.5 h-3.5" />
              Export PDF
            </button>
          </div>
        }
      />

      {/* Report document */}
      <div className="hl-card rounded-xl overflow-hidden max-w-4xl">
        {/* Report header */}
        <div className="px-8 py-6 border-b border-[#DCE3E8]" style={{ background: '#071A2B' }}>
          <div className="flex items-start justify-between">
            <div>
              <div className="flex items-center gap-2.5 mb-4">
                <div className="w-8 h-8 rounded-lg grid place-items-center" style={{ background: '#1677C8' }}>
                  <Anchor className="w-4 h-4 text-white" />
                </div>
                <span className="text-lg font-bold text-white tracking-tight">Harborline</span>
              </div>
              <h1 className="text-xl font-bold text-white mb-1">Daily Port Operations Brief</h1>
              <p className="text-sm text-white/60">JNPA / Nhava Sheva · {dateStr} · {timeStr} PST</p>
            </div>
            <div className="text-right">
              <p className="text-[10px] font-bold text-white/40 uppercase tracking-wider mb-1">Classification</p>
              <p className="text-[12px] font-bold text-white/70">OPERATIONAL USE</p>
              <p className="text-[10px] text-white/40 mt-1">Generated by Harborline</p>
            </div>
          </div>
        </div>

        <div className="px-8 py-6 space-y-8">
          {/* Situation */}
          <section>
            <div className="flex items-center gap-2 mb-4">
              <div className="w-1 h-6 rounded-full" style={{ background: '#DC2626' }} />
              <h2 className="text-[15px] font-bold text-[#071A2B] uppercase tracking-wider">Situation</h2>
            </div>
            <div className="px-4 py-4 rounded-xl" style={{ background: '#FEE2E2', border: '1px solid #FECACA' }}>
              <p className="text-sm text-[#071A2B] leading-relaxed font-medium">
                Elevated congestion risk is present across the JNPA / Nhava Sheva complex over the next 24 hours.
                Congestion probability is estimated at <strong>72%</strong> — classified as HIGH.
                Vessel arrivals are running <strong>+18% above forecast</strong>.
                Anchorage queue stands at <strong>12 vessels</strong>, up from a 30-day baseline of 8.6.
              </p>
            </div>
          </section>

          {/* Key signals */}
          <section>
            <div className="flex items-center gap-2 mb-4">
              <div className="w-1 h-6 rounded-full" style={{ background: '#1677C8' }} />
              <h2 className="text-[15px] font-bold text-[#071A2B] uppercase tracking-wider">Key Signals</h2>
            </div>
            <div className="space-y-2">
              {[
                { icon: TrendingUp, label: 'Vessel arrivals', value: '+18% above forecast baseline', severity: 'warn' },
                { icon: AlertTriangle, label: 'Anchorage queue', value: '12 vessels — +40% above 30-day average', severity: 'warn' },
                { icon: TrendingUp, label: 'Berth utilisation — Terminal A', value: '95% — approaching capacity limit', severity: 'crit' },
                { icon: CheckCircle2, label: 'Crane availability', value: '8 of 10 cranes operational — within normal range', severity: 'ok' },
                { icon: AlertTriangle, label: 'Schedule conflict', value: 'VSL-204 / VSL-307 overlap at B03 · 16:30 today', severity: 'warn' },
                { icon: CheckCircle2, label: 'Data feed status', value: 'IMF PortWatch — live · Last updated 09:42', severity: 'ok' },
              ].map((sig, i) => {
                const Icon = sig.icon;
                const cfg = sig.severity === 'crit' ? { text: '#DC2626', bg: '#FEE2E2' }
                  : sig.severity === 'warn' ? { text: '#D97706', bg: '#FEF3C7' }
                  : { text: '#16A34A', bg: '#DCFCE7' };
                return (
                  <div key={i} className="flex items-start gap-3 py-2.5 border-b border-[#DCE3E8] last:border-0">
                    <Icon className="w-4 h-4 shrink-0 mt-0.5" style={{ color: cfg.text }} />
                    <div className="flex-1 flex items-center justify-between gap-4">
                      <span className="text-[12px] font-semibold text-[#071A2B]">{sig.label}</span>
                      <span className="text-[12px] text-[#617080] text-right">{sig.value}</span>
                    </div>
                  </div>
                );
              })}
            </div>
          </section>

          {/* Recommended actions */}
          <section>
            <div className="flex items-center gap-2 mb-4">
              <div className="w-1 h-6 rounded-full" style={{ background: '#16A34A' }} />
              <h2 className="text-[15px] font-bold text-[#071A2B] uppercase tracking-wider">Recommended Actions</h2>
            </div>
            <div className="space-y-3">
              {[
                { priority: 'IMMEDIATE', action: 'Redirect next 2 vessel arrivals to Terminal B — Berth B05/B06 available', icon: AlertTriangle, color: '#DC2626' },
                { priority: 'SHORT-TERM', action: 'Move VSL-204 from B03 → B05 to resolve 16:30 schedule conflict. Expected wait time: −18 min', icon: CheckCircle2, color: '#1677C8' },
                { priority: 'SHORT-TERM', action: 'Notify pilot dispatch: stagger next 3 arrivals by +2 hours to prevent anchorage overcrowding', icon: CheckCircle2, color: '#1677C8' },
                { priority: '72-HOUR PLAN', action: 'Generate updated 72-hour berth allocation using IBM Bob optimizer to manage projected surge', icon: CheckCircle2, color: '#16A34A' },
              ].map((item, i) => {
                const Icon = item.icon;
                return (
                  <div key={i} className="flex items-start gap-3 px-4 py-3 rounded-lg bg-[#F7F7F5] border border-[#DCE3E8]">
                    <Icon className="w-4 h-4 shrink-0 mt-0.5" style={{ color: item.color }} />
                    <div>
                      <span className="text-[10px] font-bold uppercase tracking-wider mr-2" style={{ color: item.color }}>{item.priority}</span>
                      <span className="text-[12px] text-[#617080]">{item.action}</span>
                    </div>
                  </div>
                );
              })}
            </div>
          </section>

          {/* 72-hour outlook */}
          <section>
            <div className="flex items-center gap-2 mb-4">
              <div className="w-1 h-6 rounded-full" style={{ background: '#D97706' }} />
              <h2 className="text-[15px] font-bold text-[#071A2B] uppercase tracking-wider">72-Hour Outlook</h2>
            </div>
            <div className="grid grid-cols-3 gap-4">
              {[
                { horizon: '24h', prob: 83, risk: 'CRITICAL', color: '#DC2626', bg: '#FEE2E2' },
                { horizon: '48h', prob: 85, risk: 'CRITICAL', color: '#DC2626', bg: '#FEE2E2' },
                { horizon: '72h', prob: 84, risk: 'CRITICAL', color: '#DC2626', bg: '#FEE2E2' },
              ].map((item) => (
                <div key={item.horizon} className="hl-card-flat p-4 rounded-xl text-center">
                  <p className="eyebrow mb-2">+{item.horizon}</p>
                  <p className="text-3xl font-bold tabular-nums mb-1" style={{ color: item.color }}>{item.prob}%</p>
                  <span
                    className="text-[10px] font-bold px-2 py-0.5 rounded"
                    style={{ background: item.bg, color: item.color }}
                  >
                    {item.risk}
                  </span>
                </div>
              ))}
            </div>
          </section>

          {/* Footer */}
          <div className="pt-4 border-t border-[#DCE3E8] flex items-center justify-between">
            <p className="text-[11px] text-[#98A8B4]">
              Generated by Harborline · IMF PortWatch data feed · {dateStr} {timeStr}
            </p>
            <div className="flex items-center gap-2">
              <FileText className="w-3.5 h-3.5 text-[#98A8B4]" />
              <p className="text-[11px] text-[#98A8B4]">OPS-BRIEF-{today.toISOString().slice(0, 10)}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
